name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: go run -v ./scripts/catalog.go
      
    - name: Commit files
      run: |
        git config --local user.name "auto-catalog[bot]"
        git config --local user.email "auto-catalog[bot]@users.noreply.github.com"
        git commit -a -m 'Automated catalog update'
      continue-on-error: true
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: '[Bot] Automated catalog update'
        committer: GitHub <noreply@github.com>
        author: auto-catalog[bot] <auto-catalog[bot]@users.noreply.github.com>
        # 对应的上传分支
        branch: t/bot/auto-catalog
